import type { Content } from '@/lib/types/content';

export const en: Content = {
  nav: {
    about: 'About',
    how: 'How I work',
    stack: 'Stack',
    experience: 'Experience',
    projects: 'Projects',
    education: 'Education',
    contact: 'Contact',
  },
  hero: {
    role: 'Senior Frontend Engineer (Angular) | Strong Middle React Developer | Strong Middle Full-Stack Engineer (Angular + Node.js)',
    firstName: 'Pavel',
    lastName: 'Tseluiko',
    location: 'Kyiv, Ukraine - open to remote',
    pitch:
      'I build scalable full-stack products. 8+ years of experience, team leadership, mentoring intern/junior developers.',
    ctaResume: 'Download résumé - PDF',
    ctaContact: 'Get in touch',
  },
  metrics: [
    { id: 'years', value: 8, suffix: '+', label: 'Years in production' },
    { id: 'products', value: 10, suffix: '+', label: 'Products shipped end to end' },
    { id: 'companies', value: 4, label: 'Companies, enterprise and product' },
    { id: 'ecosystems', value: 2, label: 'Frontend ecosystems in depth - React & Angular' },
  ],
  about: {
    label: 'About',
    statement: 'I own features from start to finish.',
    paragraphs: [
      'Full-Stack JavaScript developer with 8+ years in enterprise and business applications. I design REST APIs and database schemas on Node.js, NestJS, TypeORM and PostgreSQL, and build scalable frontend architecture in React and Angular.',
      "I lead teams and mentor junior developers. When requirements are incomplete I don't wait for them - I reason from the end user, propose the missing behaviour and ship it. AI-assisted development is part of my daily workflow.",
    ],
    facts: [
      { key: 'Based in', value: 'Kyiv, Ukraine' },
      { key: 'Format', value: 'Remote' },
      { key: 'Languages', value: 'Ukrainian C1 · English B2' },
    ],
  },
  how: {
    label: 'How I work',
    lead: 'How I take a feature from requirement to production.',
    principles: [
      {
        id: 'understand',
        title: 'Understanding the requirement',
        body: 'I start by clarifying the business need with the PM/stakeholders and reviewing designs in Figma, making sure edge cases and API contracts are clear before writing any code.',
      },
      {
        id: 'plan',
        title: 'Planning the implementation',
        body: 'I break the task into smaller, testable pieces, decide on component structure and state management approach (NgRx/Redux, services, or local state), and estimate effort during Planning.',
      },
      {
        id: 'develop',
        title: 'Development',
        body: "I write clean, reusable, well-typed components following the project's architecture patterns, integrate with REST APIs, and cover critical logic with unit tests as I go.",
      },
      {
        id: 'review',
        title: 'Code review & collaboration',
        body: "I open a PR, walk teammates through non-trivial decisions, and actively review others' code - this catches issues early and keeps the codebase consistent.",
      },
      {
        id: 'debug',
        title: 'Debugging & iteration',
        body: 'When issues arise (in dev, staging, or production), I reproduce the bug, use browser dev tools/logs to isolate the root cause, fix it, and add a test to prevent regression.',
      },
      {
        id: 'ai',
        title: 'AI as leverage',
        body: 'AI-assisted workflows for scaffolding, refactors and tests - reviewed with exactly the same rigour as hand-written code.',
      },
    ],
  },
  stack: {
    label: 'Stack',
    lead: 'Tools I reach for, grouped by where they live.',
    groups: [
      {
        id: 'frontend',
        label: 'Frontend',
        items: [
          { label: 'React', logo: 'react' },
          { label: 'TypeScript', logo: 'typescript' },
          { label: 'Next.js', logo: 'nextdotjs' },
          { label: 'Angular', logo: 'angular' },
          { label: 'RxJS', logo: 'reactivex' },
          { label: 'NgRx', logo: 'ngrx' },
          { label: 'Redux', logo: 'redux' },
          { label: 'Zustand' },
          { label: 'TanStack Query', logo: 'reactquery' },
          { label: 'Context API' },
          { label: 'React Native (Expo)', logo: 'expo' },
          { label: 'Ionic', logo: 'ionic' },
          { label: 'PrimeNG' },
          { label: 'Angular Material', logo: 'materialdesign' },
          { label: 'CSS / SASS', logo: 'sass' },
        ],
      },
      {
        id: 'backend',
        label: 'Backend & data',
        items: [
          { label: 'Node.js', logo: 'nodedotjs' },
          { label: 'NestJS', logo: 'nestjs' },
          { label: 'TypeORM', logo: 'typeorm' },
          { label: 'PostgreSQL', logo: 'postgresql' },
          { label: 'REST APIs' },
          { label: 'Swagger / OpenAPI', logo: 'swagger' },
          { label: 'WebSockets', logo: 'socketdotio' },
          { label: 'Firebase (Firestore, Functions)', logo: 'firebase' },
          { label: 'Keycloak', logo: 'keycloak' },
          { label: 'Supabase', logo: 'supabase' },
        ],
      },
      {
        id: 'testing',
        label: 'Testing',
        items: [
          { label: 'Jest', logo: 'jest' },
          { label: 'React Testing Library', logo: 'testinglibrary' },
          { label: 'Unit & component testing' },
        ],
      },
      {
        id: 'tools',
        label: 'Tools & practices',
        items: [
          { label: 'Nx monorepo', logo: 'nx' },
          { label: 'Docker', logo: 'docker' },
          { label: 'CI/CD - Bitbucket Pipelines', logo: 'bitbucket' },
          { label: 'Git', logo: 'git' },
          { label: 'Stripe', logo: 'stripe' },
          { label: 'PayPal', logo: 'paypal' },
          { label: 'Twilio', logo: 'twilio' },
          { label: 'Google Maps API', logo: 'googlemaps' },
          { label: 'Code review' },
          { label: 'Mentoring' },
          { label: 'AI-assisted development' },
        ],
      },
    ],
  },
  experience: {
    label: 'Experience',
    lead: 'Eight years, four companies, one throughline: ownership.',
    entries: [
      {
        id: 'myreinhausen',
        company: 'MyReinhausen',
        role: 'Full-Stack JavaScript Developer',
        period: 'Nov 2021 - Jul 2026',
        tag: 'Enterprise',
        bullets: [
          'Owned frontend and backend of the customer platform: application architecture, feature delivery, technical decisions, code quality and UI consistency.',
          'Designed REST APIs with Node.js, NestJS and TypeORM - controllers, services, validated DTOs, guards, interceptors and centralised error handling.',
          'Designed the PostgreSQL schema: TypeORM entities and relations, migrations, and query optimisation through indexes, pagination and N+1 elimination.',
          'Implemented server-side authentication and authorisation with Keycloak: JWT validation, role-based guards and endpoint protection aligned with frontend permissions.',
          'Structured the codebase as an Nx monorepo with shared type and DTO libraries for end-to-end type safety, plus Docker Compose environments used across the team.',
          'Built the customer portal in Angular, TypeScript, RxJS, NgRx and PrimeNG: complex business workflows, reactive forms, reporting modules and role-based interfaces, with server-side Excel and PDF report generation.',
          'Drove architectural decisions with the team and mentored intern and junior developers through code review and pair programming.',
        ],
        stack: [
          'Node.js',
          'NestJS',
          'TypeORM',
          'PostgreSQL',
          'Swagger/OpenAPI',
          'Keycloak',
          'Docker',
          'Nx',
          'Angular',
          'TypeScript',
          'RxJS',
          'NgRx',
          'PrimeNG',
          'Jest',
        ],
      },
      {
        id: 'procoders',
        company: 'Procoders',
        role: 'Lead Frontend Developer / JavaScript Developer',
        period: 'Apr 2021 - Nov 2021',
        tag: 'Team lead',
        bullets: [
          'Acted as lead frontend developer: planned and delegated tasks, reviewed code and coordinated feature delivery across the team.',
          'Built an e-commerce platform in Angular and NgRx for a Portuguese client: catalog, cart, checkout, discount system, admin panel with change logs and Telegram order notifications.',
          'Integrated Stripe and PayPal payments plus Google and Facebook login; shipped the same application as an Ionic mobile app to the App Store and Google Play.',
          'Built a delivery application with live order tracking, estimated delivery time and real-time courier positions on the map.',
          'Built Firebase Cloud Functions on Node.js - notifications, email, barcode scanning support and backend automation - and set up CI/CD on Bitbucket Pipelines.',
        ],
        stack: [
          'Angular',
          'Ionic',
          'TypeScript',
          'NgRx',
          'Firebase',
          'Node.js',
          'Stripe',
          'PayPal',
          'Google Maps API',
          'Telegram API',
          'Bitbucket Pipelines',
        ],
      },
      {
        id: 'darly',
        company: 'Darly Solutions',
        role: 'JavaScript Developer',
        period: 'Sep 2019 - Apr 2021',
        tag: 'Four products',
        intro:
          'Four business applications: reusable UI components, dashboards, account management, complex forms, role-based access control and file uploads.',
        bullets: [
          'Advertising platform (React, TypeScript) - account and campaign creation, budget management, complex multi-step forms, Context API state, REST integration.',
          'Logistics mobile app for the US market (React Native, Redux) - cargo management workflows, vehicle selection, REST and WebSocket integrations.',
          'Travel agency platform (Next.js, TypeScript) - tour search and filtering, booking flow, authentication, server-side rendered pages, tested with Jest and React Testing Library.',
          'Platform for sports organisations (Angular) - club creation and management, chats and SMS via Twilio, real-time notifications over WebSockets, comments module.',
        ],
        stack: [
          'React',
          'React Native',
          'Next.js',
          'Angular',
          'TypeScript',
          'Redux',
          'Context API',
          'Twilio API',
          'WebSockets',
          'Jest',
          'React Testing Library',
        ],
      },
      {
        id: 'bonum',
        company: 'Bonum Studio',
        role: 'Front-end Web Developer',
        period: 'Mar 2018 - May 2019',
        tag: 'Where it started',
        bullets: [
          'Built responsive, cross-browser websites with HTML, CSS/SASS, Bootstrap, JavaScript and jQuery, using Webpack/Gulp build pipelines and WordPress.',
        ],
        stack: [
          'HTML',
          'CSS/SASS',
          'Bootstrap',
          'JavaScript',
          'jQuery',
          'Webpack',
          'Gulp',
          'WordPress',
        ],
      },
    ],
  },
  projects: {
    label: 'Projects',
    lead: 'Selected work, filtered by stack.',
    filters: { all: 'All', react: 'React', angular: 'Angular', node: 'Node.js', mobile: 'Mobile' },
    items: [
      {
        id: 'myreinhausen',
        title: 'Customer Platform',
        meta: 'MyReinhausen · 2021 - 2026',
        tags: ['angular', 'node'],
        body: 'An enterprise energy-sector customer portal owned end to end: NestJS API, PostgreSQL schema and migrations, Keycloak authentication, and an Angular front end with reporting modules and role-based interfaces.',
        stack: ['NestJS', 'TypeORM', 'PostgreSQL', 'Keycloak', 'Nx', 'Angular', 'NgRx', 'PrimeNG'],
      },
      {
        id: 'super-express',
        title: 'Super Express',
        meta: 'Procoders · 2021',
        tags: ['angular', 'node', 'mobile'],
        body: 'An online supermarket for a Portuguese client - web storefront, admin panel and an Ionic mobile app, plus a separate delivery app with real-time courier tracking, ETA and live location on the map.',
        stack: ['Angular', 'RxJS', 'Ionic', 'Node.js', 'Express.js', 'Firebase', 'Stripe', 'PayPal', 'Maps API'],
      },
      {
        id: 'sports-platform',
        title: 'Sports Events Platform',
        meta: 'Darly Solutions · 2019 - 2021',
        tags: ['angular', 'node'],
        body: 'A platform for organising sports events: event creation and scheduling, user profiles, real-time notifications and comments, chat and SMS verification via Twilio, and Google sign-in.',
        stack: ['Angular', 'Angular Material', 'RxJS', 'Node.js', 'Express.js', 'WebSockets', 'Twilio', 'Google OAuth'],
      },
      {
        id: 'vpn-saas',
        title: 'VPN Subscriptions SaaS',
        meta: 'Darly Solutions · 2019 - 2021',
        tags: ['angular'],
        body: 'A SaaS app for managing VPN access - Stripe-based paid subscriptions unlock more capabilities, with a free tier for basic use.',
        stack: ['Angular', 'RxJS', 'PHP', 'Stripe'],
      },
      {
        id: 'us-logistics',
        title: 'US Logistics App',
        meta: 'Darly Solutions · 2019 - 2021',
        tags: ['react', 'mobile'],
        body: 'A logistics app for the US market - pick the right vehicle for a given cargo and date, set pickup and drop-off, and manage shipments end to end.',
        stack: ['React', 'React Native', 'Redux', 'Context API', 'Hooks'],
      },
      {
        id: 'ad-platform',
        title: 'Advertising Platform',
        meta: 'Darly Solutions · 2019 - 2021',
        tags: ['react'],
        body: 'A platform for advertising agencies - build campaigns within a set budget through complex multi-step forms, with account and campaign management.',
        stack: ['React', 'TypeScript', 'Context API', 'Hooks', 'Tailwind CSS'],
      },
      {
        id: 'pavel-portfolio',
        title: 'Personal Portfolio',
        meta: 'Personal project · 2026',
        tags: ['react'],
        body: 'A portfolio website about me: bilingual content, stack filtering, animated sections and a responsive React interface built to present experience, projects and contact details clearly.',
        stack: ['React', 'Next.js', 'TypeScript', 'Zustand', 'TanStack Query', 'Tailwind CSS'],
      },
      {
        id: 'noveshex-fitness-platform',
        title: 'Noveshex Fitness Platform',
        meta: 'Personal project · In development',
        tags: ['react', 'mobile'],
        body: 'My personal fitness platform, currently in development: React and React Native apps for training, nutrition, supplements and progress workflows.',
        stack: ['React', 'React Native', 'Expo', 'TypeScript'],
      },
      {
        id: 'mama-travel',
        title: 'Mama Travel',
        meta: 'Darly Solutions · 2019 - 2021',
        tags: ['angular'],
        body: 'A travel-agency website with tour search, browsing and a booking flow.',
        stack: ['Angular', 'RxJS', 'PHP'],
      },
      {
        id: '5-ocean',
        title: '5 Ocean',
        meta: 'Bonum Studio · 2018 - 2019',
        tags: [],
        body: 'A responsive, cross-browser marketing website for a travel agency - hand-built and mobile-first.',
        stack: ['HTML', 'SCSS', 'JavaScript', 'jQuery', 'Webpack'],
      },
      {
        id: 'kholst',
        title: 'Kholst',
        meta: 'Bonum Studio · 2018 - 2019',
        tags: [],
        body: 'A single-page landing to order custom canvases - upload a photo and preview it printed on canvas.',
        stack: ['HTML', 'SCSS', 'JavaScript', 'jQuery', 'Webpack'],
      },
      {
        id: 'polyhim',
        title: 'Polyhim',
        meta: 'Bonum Studio · 2018 - 2019',
        tags: [],
        body: 'A multi-page website for an agriculture supplier - ordering films, drip irrigation, netting and other agro goods.',
        stack: ['HTML', 'SCSS', 'JavaScript', 'jQuery', 'Webpack', 'WordPress'],
      },
    ],
  },
  education: {
    label: 'Education',
    degreeKey: 'Degree',
    degree: "Bachelor's Degree in Programming Engineering",
    school: 'Admiral Makarov National University of Shipbuilding',
    languagesKey: 'Languages',
    languages: ['Ukrainian - C1', 'English - B2'],
    hobbiesKey: 'Off the clock',
    hobbies: 'Books · Gym · Travelling',
  },
  contact: {
    label: 'Contact',
    headline: "Let's create something meaningful - something that truly matters.",
    sub: 'Open to Middle/Senior Full-Stack and Frontend roles, remote. Email/LinkedIn is the fastest way to reach me.',
    email: 'pavel.tseluiko@gmail.com',
    phone: '+380 99 517 81 57',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    resume: 'Résumé PDF',
  },
  footer: {
    built: 'Designed and built by Pavel Tseluiko',
    stack: 'Next.js · TypeScript · Zustand · TanStack Query · NestJS · Supabase',
  },
};
